[project]
name = 'stacks-2-1-testing'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
